#define IDH_OPT_DA_ADDR_COL             1013
#define IDH_OPT_DA_CODE_COL             1014
#define IDH_OPT_DA_INSTR_COL            1015
#define IDH_OPT_HELP_CHM                1181
#define IDH_OPT_HELP_HTM                1182 
#define IDH_OPT_SYM_PROTECT_MEM         2110
#define IDH_OPT_ED_EXAMPLE              2111
#define IDH_OPT_ED_ELEMENT              2112
#define IDH_OPT_ED_BOLD_FONT            2113
#define IDH_OPT_ED_COLOR                2114
#define IDH_OPT_SYM_FIN_FF              2300
#define IDH_OPT_ASM_CASE_Y              2301
#define IDH_OPT_SYM_IO_ENABLE           2302
#define IDH_OPT_ED_AUTO_SYNTAX          2303
#define IDH_OPT_DA_CODE                 2204
#define IDH_OPT_ASM_CASE_N              2304
#define IDH_OPT_SYM_IO_ADDR             2305
#define IDH_OPT_ED_AUTO_UPPER_CASE      2206
#define IDH_OPT_SYM_PROT_FROM           2306
#define IDH_OPT_ED_NEW_FILE             2207
#define IDH_OPT_SYM_PROT_TO             2307
#define IDH_OPT_BUS_SPIN                2308
#define IDH_OPT_BUS_WIDTH               2309
#define IDH_OPT_ED_FONT_BTN             2310
#define IDH_OPT_SYM_W_SPIN              2311
#define IDH_OPT_ED_FONT_NAME            2312
#define IDH_OPT_SYM_H_SPIN              2313
#define IDH_OPT_ED_TAB_STEP             2314
#define IDH_OPT_SYM_FONT_BTN            2315
#define IDH_OPT_ED_AUTO_INDENT          2316
#define IDH_OPT_SYM_FONT_NAME           2217
#define IDH_OPT_ED_COLOR_SYNTAX         2317
#define IDH_OPT_SYM_FIN_BRK             2318
#define IDH_OPT_SYM_FIN_RTS             2319
#define IDH_OPT_ED_TAB_SPIN             2320
#define IDH_OPT_SYM_FIN                 2321
#define IDH_OPT_MARK_PTR_COL            2322
#define IDH_OPT_MARK_BRKP_COL           2323
#define IDH_OPT_MARK_ERR_COL            2324
#define IDH_OPT_SYM_IO_WND_W            2325
#define IDH_OPT_SYM_IO_WND_H            2326
#define IDH_OPT_SYM_WND_TXT_COL         2327
#define IDH_OPT_SYM_WND_BGND_COL        2328
#define IDH_OPT_6502                    2330
#define IDH_OPT_65C02                   2331
#define IDH_OPT_65816                   2332
#define IDH_OPT_ASM_INSTR_DOT           2333
#define IDH_OPT_ASM_GENERATE_LIST       2334
#define IDH_OPT_ASM_FILE_LISTING        2335
#define IDH_OPT_ASM_GENERATE_BYTE       2336
#define IDH_OPT_ASM_EXTRA_BYTE          2337
#define IDH_OPT_ASM_CHOOSE_FILE         2338
#define IDH_OPT_FONT_BTN                2339
#define IDH_OPT_FONT_NAME               2340
#define IDH_OPT_VIEW_BKGND_COL          2329
#define IDH_OPT_VIEW_WND                2341
#define IDH_OPT_VIEW_TXT_COL            2342
#define IDH_OPT_VIEW_EXAMPLE            2343
#define IDH_OPT_VIEW_FONT_BTN           2344
#define IDH_OPT_VIEW_FONT_NAME          2345
